// Merges the research lane files into data/places.js.
// Usage: node scripts/build-data.mjs <dir-with-*.ru.json|*.verified.json|*.json>
// Preference order per lane: <lane>.ru.json > <lane>.verified.json > <lane>.json
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = process.argv[2] || path.join(root, 'research');
const files = fs.readdirSync(dir).filter(f => f.endsWith('.json'));
const lanes = {};
for (const f of files) {
  const m = f.match(/^(.+?)(\.verified|\.ru)?\.json$/); if (!m) continue;
  const lane = m[1]; const rank = m[2] === '.ru' ? 3 : (m[2] === '.verified' ? 2 : 1);
  if (!lanes[lane] || lanes[lane].rank < rank) lanes[lane] = { rank, file: f };
}
const CATS = new Set(['see', 'museum', 'show', 'eat', 'drink', 'cafe', 'shop', 'park', 'walk', 'daytrip']);
const seen = new Map(); const out = []; const problems = [];
const slug = (s) => String(s).toLowerCase().normalize('NFD').replace(/[̀-ͯ]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
for (const lane of Object.keys(lanes).sort()) {
  const j = JSON.parse(fs.readFileSync(path.join(dir, lanes[lane].file), 'utf8'));
  const arr = Array.isArray(j) ? j : (j.places || []);
  for (const raw of arr) {
    const p = Object.assign({}, raw);
    p.id = slug(p.id || p.name); p.lane = lane;
    if (!CATS.has(p.cat)) { problems.push(`${lane}/${p.id}: bad cat ${p.cat}`); p.cat = p.cat === 'event' ? 'show' : 'see'; }
    p.lat = Number(p.lat); p.lng = Number(p.lng); p.dur = Number(p.dur) || 60;
    if (!(p.lat > 40.49 && p.lat < 40.92 && p.lng > -74.27 && p.lng < -73.68)) { problems.push(`${lane}/${p.id}: coords ${p.lat},${p.lng} outside NYC — dropped`); continue; }
    for (const u of ['web', 'tickets', 'reserve', 'menu', 'ig']) { if (p[u] && !/^https?:\/\//.test(p[u])) { problems.push(`${lane}/${p.id}: ${u} not a URL (${p[u]}) — blanked`); p[u] = ''; } if (p[u] == null) p[u] = ''; }
    p.closed = Array.isArray(p.closed) ? p.closed.map(x => String(x).toLowerCase().slice(0, 3)).filter(x => ['mon', 'tue', 'wed', 'thu', 'fri', 'sat', 'sun'].includes(x)) : [];
    p.tags = Array.isArray(p.tags) ? p.tags : []; p.tips = Array.isArray(p.tips) ? p.tips : [];
    if (p.tipsRu && !Array.isArray(p.tipsRu)) delete p.tipsRu;
    if (seen.has(p.id)) {
      // keep the richer record, merge blanks
      const prev = seen.get(p.id); for (const k of Object.keys(p)) if ((prev[k] == null || prev[k] === '' || (Array.isArray(prev[k]) && !prev[k].length)) && p[k]) prev[k] = p[k];
      problems.push(`${lane}/${p.id}: duplicate of ${prev.lane}/${p.id} — merged`); continue;
    }
    seen.set(p.id, p); out.push(p);
  }
}
out.sort((a, b) => a.cat.localeCompare(b.cat) || a.name.localeCompare(b.name));
const header = `// ============================================================================
// PLACES — the library. Generated by scripts/build-data.mjs from the research
// lanes (${Object.keys(lanes).sort().join(', ')}) on ${new Date().toISOString().slice(0, 10)}.
// Hours, prices and links were compiled from model knowledge + Sep-2026 search
// extracts and are NOT live-verified: "conf" says how sure we were. Edit freely.
// ============================================================================
`;
const body = '[\n' + out.map(p => JSON.stringify(p)).join(',\n') + '\n]';
fs.writeFileSync(path.join(root, 'data', 'places.js'), header + 'window.PLACES = ' + body + ';\n');
console.log(`wrote data/places.js with ${out.length} places from ${Object.keys(lanes).length} lanes`);
const byCat = {}; out.forEach(p => { byCat[p.cat] = (byCat[p.cat] || 0) + 1; }); console.log(byCat);
if (problems.length) { console.log('\nproblems:'); problems.forEach(p => console.log(' - ' + p)); }
