// Merges the Russian/German translation batches into data/places.js.
// Usage: node scripts/merge-i18n.mjs <dir-of-batch-*.json>
// Safe to re-run: it rewrites the translated fields and leaves everything else alone.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const dir = process.argv[2];
if (!dir) { console.error('usage: node scripts/merge-i18n.mjs <dir>'); process.exit(1); }

const require = createRequire(import.meta.url);
const w = {}; global.window = w;
require(path.join(root, 'data/places.js'));
const places = w.PLACES;

const T = {};
let files = 0;
for (const f of fs.readdirSync(dir).filter(f => /^batch-\d+\.json$/.test(f)).sort()) {
  Object.assign(T, JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8')));
  files++;
}

const STR = ['nameRu', 'nameDe', 'subRu', 'subDe', 'whyRu', 'whyDe', 'hoursRu', 'hoursDe', 'priceRu', 'priceDe', 'leadRu', 'leadDe'];
const ARR = ['tipsRu', 'tipsDe'];
const problems = [];
let touched = 0, missing = [];

for (const p of places) {
  const t = T[p.id];
  if (!t) { missing.push(p.id); continue; }
  let did = false;
  for (const f of STR) {
    const v = t[f];
    if (typeof v === 'string' && v.trim()) { p[f] = v.trim(); did = true; }
  }
  for (const f of ARR) {
    const v = t[f];
    if (Array.isArray(v) && v.length) {
      if (v.length !== (p.tips || []).length) problems.push(`${p.id}: ${f} has ${v.length} entries, tips has ${(p.tips || []).length} — dropped`);
      else { p[f] = v.map(String); did = true; }
    }
  }
  // Prices must keep their dollar amounts: a translation that changes a number is a bug.
  for (const [src, dst] of [['price', 'priceRu'], ['price', 'priceDe']]) {
    if (p[src] && p[dst]) {
      // Compare the numbers only: a comma that belongs to the sentence ("$20, or…")
      // is not a change to the amount, and the naive match swallowed it.
      const amounts = (t) => (t.match(/\$\s?[\d][\d,.]*/g) || []).map(x => x.replace(/[.,]+$/, '').replace(/\s/g, '')).join('|');
      const a = amounts(p[src]);
      const b = amounts(p[dst]);
      if (a !== b) { problems.push(`${p.id}: ${dst} changed the amounts (${a} → ${b}) — reverted`); delete p[dst]; }
    }
  }
  if (did) touched++;
}

const header = `// ============================================================================
// PLACES — the library, in English, Russian and German. Generated by
// scripts/build-data.mjs and translated by scripts/merge-i18n.mjs
// on ${new Date().toISOString().slice(0, 10)}.
// Hours, prices and links were compiled from research and model knowledge and
// are NOT live-verified: "conf" says how sure we were. Edit freely.
// ============================================================================
`;
fs.writeFileSync(path.join(root, 'data', 'places.js'), header + 'window.PLACES = ' + JSON.stringify(places, null, 1) + ';\n');

const cov = (f) => places.filter(p => p[f] && String(p[f]).trim()).length;
console.log(`merged ${files} batch files into ${places.length} places (${touched} touched)`);
console.log(`coverage: whyRu ${cov('whyRu')}/${places.length}, whyDe ${cov('whyDe')}/${places.length}, tipsRu ${places.filter(p => (p.tipsRu || []).length).length}, tipsDe ${places.filter(p => (p.tipsDe || []).length).length}`);
if (missing.length) console.log(`no translation for ${missing.length}: ${missing.slice(0, 20).join(', ')}${missing.length > 20 ? '…' : ''}`);
if (problems.length) { console.log('\nproblems:'); problems.forEach(p => console.log(' - ' + p)); }
